name: amusement_02
sha1: e7d71e83cde6967816469e932d137ed136c1fb6c
options:
  basename: amusement_02
  elf_path: amusement_02.bin
  target_path: rom/overlay/amusement_02.bin
  find_file_boundaries: False
  asm_path: asm
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/amusement_02_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: amusement_02_reloc_addrs.txt
  ld_script_path: linkers/amusement_02.ld
  undefined_funcs_auto_path: linkers/amusement_02_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/amusement_02_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, amusement_02_overlay_header]
  - name: amusement_02
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x4500
    subsegments:
      - [0x80, c, Event/amusement_02]
      - [0x2500, data, amusement_02_data]
      - { vram: 0x1F76680, type: bss, name: amusement_02_bss }
  - [0x9080]
