name: apart_00
sha1: ced9de85b908dfb9d4cce0c9e405397cb3dbb3d7
options:
  basename: apart_00
  elf_path: apart_00.bin
  target_path: rom/overlay/apart_00.bin
  find_file_boundaries: False
  asm_path: asm/apart_00
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/apart_00_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: apart_00_reloc_addrs.txt
  ld_script_path: linkers/apart_00.ld
  undefined_funcs_auto_path: linkers/apart_00_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/apart_00_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, apart_00_overlay_header]
  - name: apart_00
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x80
    subsegments:
      - [0x80, c, Event/apart_00]
      - [0x1600, data, apart_00_data]
      - { vram: 0x1F70000, type: bss, name: apart_00_bss }
  - [0x2A00]
