name: building_f_02
sha1: b7ed39bdf3f814ba9234f0686a4fa2dfab4343b4
options:
  basename: building_f_02
  elf_path: building_f_02.bin
  target_path: rom/overlay/building_f_02.bin
  find_file_boundaries: False
  asm_path: asm/building_f_02
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/building_f_02_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: building_f_02_reloc_addrs.txt
  ld_script_path: linkers/building_f_02.ld
  undefined_funcs_auto_path: linkers/building_f_02_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/building_f_02_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, building_f_02_overlay_header]
  - name: building_f_02
    type: code
    vram: 0x1F6D680
    start: 0x80
    subsegments:
      - [0x80, c, Event/building_f_02]
      - [0x200, data, building_f_02_data]
  - [0x1200]
