name: building_b_00
sha1: cc1b7ebadb9ed81c1bb9640e433da1cd3511972b
options:
  basename: building_b_00
  elf_path: building_b_00.bin
  target_path: rom/overlay/building_b_00.bin
  find_file_boundaries: False
  asm_path: asm
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/building_b_00_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: building_b_00_reloc_addrs.txt
  ld_script_path: linkers/building_b_00.ld
  undefined_funcs_auto_path: linkers/building_b_00_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/building_b_00_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, building_b_00_overlay_header]
  - name: building_b_00
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x80
    subsegments:
      - [0x80, c, Event/building_b_00]
      - [0xF00, data, building_b_00_data]
      - { vram: 0x1F6FB00, type: bss, name: building_b_00_bss }
  - [0x2500]
