name: building_f_00
sha1: 8007e2cf3f7ad7a3bc7a1ed22d4ac7545db44ea7
options:
  basename: building_f_00
  elf_path: building_f_00.bin
  target_path: rom/overlay/building_f_00.bin
  find_file_boundaries: False
  asm_path: asm
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/building_f_00_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: building_f_00_reloc_addrs.txt
  ld_script_path: linkers/building_f_00.ld
  undefined_funcs_auto_path: linkers/building_f_00_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/building_f_00_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, building_f_00_overlay_header]
  - name: building_f_00
    type: code
    vram: 0x1F6D680
    start: 0x80
    subsegments:
      - [0x80, c, Event/building_f_00]
      - [0xB80, data, building_f_00_data]
  - [0x1780]
