name: building_b_01
sha1: 794ba8e58dd474c1334fe72d5a7306fc6096b99a
options:
  basename: building_b_01
  elf_path: building_b_01.bin
  target_path: rom/overlay/building_b_01.bin
  find_file_boundaries: False
  asm_path: asm
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/building_b_01_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: building_b_01_reloc_addrs.txt
  ld_script_path: linkers/building_b_01.ld
  undefined_funcs_auto_path: linkers/building_b_01_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/building_b_01_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, building_b_01_overlay_header]
  - name: building_b_01
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x80
    subsegments:
      - [0x80, c, Event/building_b_01]
      - [0xF00, data, building_b_01_data]
      - { vram: 0x1F6F100, type: bss, name: building_b_01_bss }
  - [0x1B00]
