name: car_00
sha1: 4336eeda7c246aa46c32e5d5c6605f16a3623d60
options:
  basename: car_00
  elf_path: car_00.bin
  target_path: rom/overlay/car_00.bin
  find_file_boundaries: False
  asm_path: asm/car_00
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/car_00_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: car_00_reloc_addrs.txt
  ld_script_path: linkers/car_00.ld
  undefined_funcs_auto_path: linkers/car_00_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/car_00_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, car_00_overlay_header]
  - name: car_00
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x80
    subsegments:
      - [0x80, c, Event/car_00]
      - [0x300, data, car_00_data]
      - { vram: 0x1F6DC80, type: bss, name: car_00_bss }
  - [0x680]
