name: church_01
sha1: 50a83ae7eeea257dc0c81a1433c5740769d08509
options:
  basename: church_01
  elf_path: church_01.bin
  target_path: rom/overlay/church_01.bin
  find_file_boundaries: False
  asm_path: asm
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/church_01_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: church_01_reloc_addrs.txt
  ld_script_path: linkers/church_01.ld
  undefined_funcs_auto_path: linkers/church_01_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/church_01_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, church_01_overlay_header]
  - name: church_01
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x100
    subsegments:
      - [0x80, c, Event/church_01]
      - [0x1B80, data, church_01_data]
      - { vram: 0x1F70600, type: bss, name: church_01_bss }
  - [0x3000]
