name: church_00
sha1: be98a0ee94ce34e0aa181f867b03ab5f57c52829
options:
  basename: church_00
  elf_path: church_00.bin
  target_path: rom/overlay/church_00.bin
  find_file_boundaries: False
  asm_path: asm/church_00
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/church_00_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: church_00_reloc_addrs.txt
  ld_script_path: linkers/church_00.ld
  undefined_funcs_auto_path: linkers/church_00_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/church_00_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, church_00_overlay_header]
  - name: church_00
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x80
    subsegments:
      - [0x80, c, Event/church_00]
      - [0x800, data, church_00_data]
      - { vram: 0x1F6E600, type: bss, name: church_00_bss }
  - [0x1000]
