name: hospital_b_00
sha1: eb8d5141e30d41c4671ec9241fb6abddfe99c15b
options:
  basename: hospital_b_00
  elf_path: hospital_b_00.bin
  target_path: rom/overlay/hospital_b_00.bin
  find_file_boundaries: False
  asm_path: asm/hospital_b_00
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/hospital_b_00_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: hospital_b_00_reloc_addrs.txt
  ld_script_path: linkers/hospital_b_00.ld
  undefined_funcs_auto_path: linkers/hospital_b_00_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/hospital_b_00_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, hospital_b_00_overlay_header]
  - name: hospital_b_00
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x100
    subsegments:
      - [0x80, c, Event/hospital_b_00]
      - [0x1380, data, hospital_b_00_data]
      - { vram: 0x1F70600, type: bss, name: hospital_b_00_bss }
  - [0x3000]
