name: hospital_f_01
sha1: 13d2f9c477363617e73299489336051c14353673
options:
  basename: hospital_f_01
  elf_path: hospital_f_01.bin
  target_path: rom/overlay/hospital_f_01.bin
  find_file_boundaries: False
  asm_path: asm/hospital_f_01
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/hospital_f_01_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: hospital_f_01_reloc_addrs.txt
  ld_script_path: linkers/hospital_f_01.ld
  undefined_funcs_auto_path: linkers/hospital_f_01_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/hospital_f_01_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, hospital_f_01_overlay_header]
  - name: hospital_f_01
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x80
    subsegments:
      - [0x80,   asm,  Event/hospital_f_01]
      - [0x2F00, data, hospital_f_01_data]
      - { vram: 0x1F71680, type: bss, name: hospital_f_01_bss }
  - [0x4080]
