name: hospital_f_03
sha1: dbcd3322b75f9a0da5a9bb0062270af69d54c4a7
options:
  basename: hospital_f_03
  elf_path: hospital_f_03.bin
  target_path: rom/overlay/hospital_f_03.bin
  find_file_boundaries: False
  asm_path: asm/hospital_f_03
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/hospital_f_03_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: hospital_f_03_reloc_addrs.txt
  ld_script_path: linkers/hospital_f_03.ld
  undefined_funcs_auto_path: linkers/hospital_f_03_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/hospital_f_03_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, hospital_f_03_overlay_header]
  - name: hospital_f_03
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x100
    subsegments:
      - [0x80, c, Event/hospital_f_03]
      - [0x2680, data, hospital_f_03_data]
      - { vram: 0x1F70880, type: bss, name: hospital_f_03_bss }
  - [0x3280]
