name: hospital_f_02
sha1: 93e92bf95b7485e5715e0e06412398f21d624469
options:
  basename: hospital_f_02
  elf_path: hospital_f_02.bin
  target_path: rom/overlay/hospital_f_02.bin
  find_file_boundaries: False
  asm_path: asm/hospital_f_02
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/hospital_f_02_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: hospital_f_02_reloc_addrs.txt
  ld_script_path: linkers/hospital_f_02.ld
  undefined_funcs_auto_path: linkers/hospital_f_02_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/hospital_f_02_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, hospital_f_02_overlay_header]
  - name: hospital_f_02
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x80
    subsegments:
      - [0x80, c, Event/hospital_f_02]
      - [0x1880, data, hospital_f_02_data]
      - { vram: 0x1F6FF80, type: bss, name: hospital_f_02_bss }
  - [0x2980]
