name: hospital_b_02
sha1: 062931f805a5be691ede1fc048cabb156dab087c
options:
  basename: hospital_b_02
  elf_path: hospital_b_02.bin
  target_path: rom/overlay/hospital_b_02.bin
  find_file_boundaries: False
  asm_path: asm
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/hospital_b_02_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: hospital_b_02_reloc_addrs.txt
  ld_script_path: linkers/hospital_b_02.ld
  undefined_funcs_auto_path: linkers/hospital_b_02_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/hospital_b_02_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, hospital_b_02_overlay_header]
  - name: hospital_b_02
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x80
    subsegments:
      - [0x80, c, Event/hospital_b_02]
      - [0x3280, data, hospital_b_02_data]
      - { vram: 0x1F74100, type: bss, name: hospital_b_02_bss }
  - [0x6B00]
