name: mall_b_01
sha1: 451fe6add0831ef54859fc0288c32daaa71b1773
options:
  basename: mall_b_01
  elf_path: mall_b_01.bin
  target_path: rom/overlay/mall_b_01.bin
  find_file_boundaries: False
  asm_path: asm
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/mall_b_01_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: mall_b_01_reloc_addrs.txt
  ld_script_path: linkers/mall_b_01.ld
  undefined_funcs_auto_path: linkers/mall_b_01_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/mall_b_01_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, mall_b_01_overlay_header]
  - name: mall_b_01
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x100
    subsegments:
      - [0x80, c, Event/mall_b_01]
      - [0x2000, data, mall_b_01_data]
      - { vram: 0x1F72880, type: bss, name: mall_b_01_bss }
  - [0x5280]
