name: mall_f_00
sha1: ea4d85b20f3cf6ccd396035887c5d0dd65e33716
options:
  basename: mall_f_00
  elf_path: mall_f_00.bin
  target_path: rom/overlay/mall_f_00.bin
  find_file_boundaries: False
  asm_path: asm
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/mall_f_00_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: mall_f_00_reloc_addrs.txt
  ld_script_path: linkers/mall_f_00.ld
  undefined_funcs_auto_path: linkers/mall_f_00_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/mall_f_00_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, mall_f_00_overlay_header]
  - name: mall_f_00
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x80
    subsegments:
      - [0x80, c, Event/mall_f_00]
      - [0x1000, data, mall_f_00_data]
      - { vram: 0x1F6FB80, type: bss, name: mall_f_00_bss }
  - [0x2580]
