name: subway_02
sha1: 1a12b176eef496ae28f14744f059f08f45c57c17
options:
  basename: subway_02
  elf_path: subway_02.bin
  target_path: rom/overlay/subway_02.bin
  find_file_boundaries: False
  asm_path: asm
  rodata_string_guesser_level: 0
  symbol_addrs_path:
   - overlay/subway_02_symbol_addrs.txt
   - symbol_addrs.txt
  reloc_addrs_path: subway_02_reloc_addrs.txt
  ld_script_path: linkers/subway_02.ld
  undefined_funcs_auto_path: linkers/subway_02_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/subway_02_undefined_syms_auto.main.txt
  symbol_name_format: $VRAM_$SEG
segments:

  - [0, databin, subway_02_overlay_header]
  - name: subway_02
    type: code
    vram: 0x1F6D680
    start: 0x80
    bss_size: 0x80
    subsegments:
      - [0x80,  c,    Event/subway_02]
      - [0xC00, data, subway_02_data]
      - { vram: 0x1F6F080, type: bss, name: subway_02_bss }
  - [0x1A80]
